suborgrepos:
  - automation.*

suborgteams:
  - automation

repository:
  auto_init: true
  topics:
  private: true
  has_issues: true
  has_projects: false
  has_wiki: true
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true

teams:
  - name: automation
    permission: push
  - name: automation-admins
    permission: admin
  - name: service-accounts
    permission: pull
  - name: platform
    permission: push

branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users:
            - rccl-github
          teams:
            - automation-admins
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions: null

autolinks:
  - key_prefix: "MEGA-"
    url_template: "https://jira.com/browse/MEGA-<num>"

validator:
  pattern: "[a-zA-Z0-9_-]+"