name: Org Activity Report

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'GitHub Organization'
        required: true
        default: 'rcg-digital-backend'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: jasontcrabtree/github-org-activity-report@v1
        with:
          org: ${{ github.event.inputs.org }}
          token: ${{ secrets.GITHUB_TOKEN }}
