name: Org Activity Report

on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'GitHub Organization'
        required: true
        default: 'rcg-digital-backend'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - id: scan_org
        uses: peter-murray/inactive-users-action@v1
        with:
          organization: ${{ github.event.inputs.organization }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: upload_report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: reports
          path: |
            ${{ steps.scan_org.outputs.report_csv }}
