name: Org Activity Report

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'GitHub Organization'
        required: true
        default: 'rcg-digital-backend'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-murray/inactive-users-action@v1
        with:
          organization: ${{ github.event.inputs.org }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_user_activity.outputs.report_csv }}
